Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 100

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: separator

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
