inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: separator

Lint/BooleanSymbol:
  Exclude:
    - 'lib/gemologist/ast.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/gemologist/ast_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 100

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
